core/routes/web.php
        Route::post('general-setting', 'GeneralSettingController@update')->name('setting.update');
        Route::get('optimize', 'GeneralSettingController@optimize')->name('setting.optimize');

        //Custom CSS
        Route::get('custom-css','GeneralSettingController@customCss')->name('setting.custom.css');
        Route::post('custom-css','GeneralSettingController@customCssSubmit');

        // Logo-Icon
        Route::get('setting/logo-icon', 'GeneralSettingController@logoIcon')->name('setting.logo-icon');
        Route::post('setting/logo-icon', 'GeneralSettingController@logoIconUpdate')->name('setting.logo-icon');

        // Plugin
        Route::get('extensions', 'ExtensionController@index')->name('extensions.index');
        Route::post('extensions/update/{id}', 'ExtensionController@update')->name('extensions.update');
        Route::post('extensions/activate', 'ExtensionController@activate')->name('extensions.activate');
        Route::post('extensions/deactivate', 'ExtensionController@deactivate')->name('extensions.deactivate');


        // Email Setting
        Route::get('email-template/global', 'EmailTemplateController@emailTemplate')->name('email-template.global');
        Route::post('email-template/global', 'EmailTemplateController@emailTemplateUpdate')->name('email-template.global');
        Route::get('email-template/setting', 'EmailTemplateController@emailSetting')->name('email-template.setting');
        Route::post('email-template/setting', 'EmailTemplateController@emailSettingUpdate')->name('email-template.setting');
        Route::get('email-template/index', 'EmailTemplateController@index')->name('email-template.index');
        Route::get('email-template/{id}/edit', 'EmailTemplateController@edit')->name('email-template.edit');
        Route::post('email-template/{id}/update', 'EmailTemplateController@update')->name('email-template.update');
        Route::post('email-template/send-test-mail', 'EmailTemplateController@sendTestMail')->name('email-template.sendTestMail');


        // SMS Setting
        Route::get('sms-template/global', 'SmsTemplateController@smsSetting')->name('sms-template.global');
        Route::post('sms-template/global', 'SmsTemplateController@smsSettingUpdate')->name('sms-template.global');
        Route::get('sms-template/index', 'SmsTemplateController@index')->name('sms-template.index');
        Route::get('sms-template/edit/{id}', 'SmsTemplateController@edit')->name('sms-template.edit');
        Route::post('sms-template/update/{id}', 'SmsTemplateController@update')->name('sms-template.update');
        Route::post('email-template/send-test-sms', 'SmsTemplateController@sendTestSMS')->name('email-template.sendTestSMS');



        //Report Bugs
        Route::get('request-report','AdminController@requestReport')->name('request.report');
        Route::post('request-report','AdminController@reportSubmit');

        Route::get('system-info','AdminController@systemInfo')->name('system.info');



        // SEO
        Route::get('seo', 'FrontendController@seoEdit')->name('seo');


        // Frontend
        Route::name('frontend.')->prefix('frontend')->group(function () {


            Route::get('templates', 'FrontendController@templates')->name('templates');
            Route::post('templates', 'FrontendController@templatesActive')->name('templates.active');



            Route::get('frontend-sections/{key}', 'FrontendController@frontendSections')->name('sections');
            Route::post('frontend-content/{key}', 'FrontendController@frontendContent')->name('sections.content');
            Route::get('frontend-element/{key}/{id?}', 'FrontendController@frontendElement')->name('sections.element');
            Route::post('remove', 'FrontendController@remove')->name('remove');

            // Page Builder
            Route::get('manage-pages', 'PageBuilderController@managePages')->name('manage.pages');
            Route::post('manage-pages', 'PageBuilderController@managePagesSave')->name('manage.pages.save');
            Route::patch('manage-pages', 'PageBuilderController@managePagesUpdate')->name('manage.pages.update');
            Route::delete('manage-pages', 'PageBuilderController@managePagesDelete')->name('manage.pages.delete');
            Route::get('manage-section/{id}', 'PageBuilderController@manageSection')->name('manage.section');
            Route::post('manage-section/{id}', 'PageBuilderController@manageSectionUpdate')->name('manage.section.update');
        });
    });
});

/*
|--------------------------------------------------------------------------
| Start User Area
|--------------------------------------------------------------------------
*/

Route::name('user.')->group(function () {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('logout', 'Auth\LoginController@logoutGet')->name('logout');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->middleware('regStatus');

    //Campaign
    Route::get('campaigns','CampaignController@showAll')->name('campaigns');

    Route::get('campaign/details/{slug}/{id}','CampaignController@details')->name('campaign.details');
    Route::post('campaign/details/{slug}/{id}','DonationController@donation');

    Route::post('campaign/donation/insert','DonationController@donationInsert')->name('donation.insert');
    Route::get('campaign/donation/preview','DonationController@preview')->name('donation.preview');


    Route::get('campaign/{id}','CampaignController@filterCampaign')->name('campaign.filter');
    Route::get('price/filter','CampaignController@filterCampaignByPrice')->name('price.filter');
    Route::get('date/filter','CampaignController@filterCampaignByDate')->name('date.filter');
    Route::get('search/filter','CampaignController@searchFilter')->name('search.filter');
    Route::get('campaign/checkbox/filter','CampaignController@campaignFilterByCheckbox')->name('checkbox.filter');

    // success Story
    Route::get('success/details/{slug}/{id}','SuccessStoryController@showBlog')->name('success.details');
    Route::post('success/details/{slug}/{id}','SuccessStoryController@leaveComment');
    Route::get('success/story','SuccessStoryController@blogAll')->name('success.archive');
    Route::get('success/story/search','SuccessStoryController@ajax')->name('success.ajax');

    Route::post('subscribe','SiteController@subscribe')->name('subscribe');
    // About
    Route::get('about','UserController@about')->name('about');

    // Comment
    Route::post('campaign/comments','CommentController@comment')->name('campaign.comment');

    // policy
    Route::get('site/{slug}','SiteController@policy')->name('site');

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/code-verify', 'Auth\ForgotPasswordController@codeVerify')->name('password.code_verify');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/verify-code', 'Auth\ForgotPasswordController@verifyCode')->name('password.verify-code');

    Route::get('chargers', 'Admin\PackageController@front')->name('chargers.index');

});

Route::name('user.')->prefix('user')->group(function () {
    Route::middleware('auth')->group(function () {
        Route::get('authorization', 'AuthorizationController@authorizeForm')->name('authorization');
        Route::get('resend-verify', 'AuthorizationController@sendVerifyCode')->name('send_verify_code');
        Route::post('verify-email', 'AuthorizationController@emailVerification')->name('verify_email');
        Route::post('verify-sms', 'AuthorizationController@smsVerification')->name('verify_sms');
        Route::post('verify-g2fa', 'AuthorizationController@g2faVerification')->name('go2fa.verify');

        Route::middleware(['checkStatus'])->group(function () {
            Route::get('dashboard', 'UserController@home')->name('home');
            // Fundrise
            Route::get('campaign','CampaignController@create')->name('fundrise');
            Route::post('campaign','CampaignController@storeCampaign');
            Route::get('campaign/all','CampaignController@showAllFundrise')->name('fundrise.all');

            Route::get('donation/log','DonationController@donationLog')->name('donation.log');
            Route::get('donation/details/{id}','DonationController@donationDetails')->name('donation.details');

            Route::get('campaign/edit/{slug?}/{id?}','CampaignController@editRequest')->name('fundrise.edit');
            Route::post('campaign/edit/{slug?}/{id?}','CampaignController@sendRequest');
            Route::get('campaign/stop/{id}','CampaignController@campaignStop')->name('fundrise.stop');
            Route::get('campaign/complete/{id}','CampaignController@campaignComplete')->name('fundrise.makeComplete');

            Route::get('campaign/delete/{slug}/{id}','CampaignController@delete')->name('fundrise.delete');
            Route::get('campaign/approved','CampaignController@approvedCampaign')->name('fundrise.approved');
            Route::get('campaign/rejected','CampaignController@rejectedCampaign')->name('fundrise.rejected');
            Route::get('campaign/pending','CampaignController@pending')->name('fundrise.pending');
            Route::get('campaign/success','CampaignController@complete')->name('fundrise.complete');
            Route::get('campaign/expired','CampaignController@expired')->name('fundrise.expired');

core/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'address' => 'object',
        'ver_code_send_at' => 'datetime'
    ];





    public function login_logs()
    {
        return $this->hasMany(UserLogin::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('id','desc');
    }

    public function deposits()
    {
        return $this->hasMany(Deposit::class)->where('status','!=',0);
    }

    public function withdrawals()
    {
        return $this->hasMany(Withdrawal::class)->where('status','!=',0);
    }


    // SCOPES

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function scopeBanned()
    {
        return $this->where('status', 0);
    }

    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeEmailVerified()
    {
        return $this->where('ev', 1);
    }

    public function scopeSmsVerified()
    {
        return $this->where('sv', 1);
    }

}

core/resources/views/templates/basic/sections/breadcumb.blade.php
@php
    $data = getContent('breadcumb.content',true);
    $texture = getContent('breadcumb.element',true);

@endphp
 <!-- inner-page-hero start -->
<section class="inner-page-hero bg_img" data-background="{{get_image('assets/images/frontend/breadcumb/'.@$data->data_values->image)}}">
    <div class="bottom-shape"><img src="{{asset($activeTemplateTrue.'images/top-shape.png')}}" alt="@lang('image')"></div>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6 text-center">
        <h2 class="page-title">{{__($page_title)}}</h2>
          <ul class="page-list justify-content-center">
          <li><a href="{{route('user.home')}}">@lang('Home')</a></li>
          <li class="active">{{__($page_title)}}</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- inner-page-hero end -->

core/resources/views/templates/basic/sections/campaign.blade.php
@php
    $data = getContent('campaign.content',true);
    $now = Carbon\Carbon::now();

    $campaign = App\Campaign::where('stop_status',0)->where('approval',1)->where('complete_status',0)->where('deadline','>',$now)->latest()->take(6)->get();

@endphp
<!-- event section start -->
<section class="pt-150 pb-150 position-relative base--bg">
    <div class="section-img"><img src="{{get_image($activeTemplateTrue.'images/texture-3.jpg')}}" alt="@lang('image')"></div>
    <div class="bottom-shape"><img src="{{asset($activeTemplateTrue.'images/top-shape.png')}}" alt="@lang('image')"></div>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-lg-8">
          <div class="section-header text-center">
          <h2 class="section-title text-white">{{__($data->data_values->title)}}</h2>
          <p class="text-white">{{__($data->data_values->description)}}</p>
          </div>
        </div>
      </div><!-- row end -->
      <div class="row mb-none-30">
        @foreach($campaign as $camp)
        <div class="col-lg-4 col-md-6 mb-30">
          <div class="event-card hover--effect-1 has-link">
          <a href="{{route('user.campaign.details',['slug' => $camp->slug, 'id' => $camp->id])}}" class="item-link"></a>
            <div class="event-card__thumb">
            <img src="{{get_image(imagePath()['campaign']['path'].'/'.$camp->image)}}" alt="@lang('image')" class="w-100">
            </div>
            <div class="event-card__content">
            <h4 class="title">{{Str::limit($camp->title,50)}}</h4>

            <span class="days-left mb-3 font-italic" data-deadline = {{$camp->deadline}}>
              <span class="day"></span>
              <span class="hour"></span>
              <span class="minute"></span>
              <span class="sec"></span>

            </span>
              <p class="text-justify">{{Str::limit($camp->description,120)}}</p>
              <div class="event-bar-item">
                <div class="skill-bar">
                  @php
                    $percent = ($camp->donation->where('payment_status',1)->sum('donation') * 100) / $camp->goal;
                  @endphp
                  <div class="progressbar" data-perc="{{$percent > 100 ? '100': $percent}}%">
                    <div class="bar"></div>
                    <span class="label">{{number_format(($percent > 100 ? '100': $percent),2)}}%</span>
                  </div>
                </div>
              </div><!-- event-bar-item end -->
              <div class="amount-status">
              <div class="left">@lang('Raised') - <b>{{$general->cur_sym}}  {{$camp->donation->where('payment_status',1)->sum('donation')}}</b></div>
              <div class="right">@lang('Goal') - <b>{{$general->cur_sym}} {{$camp->goal}}</b></div>
              </div>
            </div>
          </div><!-- event-card end -->
        </div>
    @endforeach

       <div class="col-md-12 mb-5 text-center">
       <a href="{{route('user.campaigns')}}" class="cmn-btn">@lang('Show All Campaign')</a>
       </div>
      </div>

    </div>
  </section>
  <!-- event section end -->


@push('script')
      <script>

        'use strict';

         $(".progressbar").each(function(){
            $(this).find(".bar").animate({
              "width": $(this).attr("data-perc")
            },3000);
            $(this).find(".label").animate({
              "left": $(this).attr("data-perc")
            },3000);
        });


        var x = setInterval(function() {
          console.log('a');
          var deadline = $('.days-left').each(function(item){

              var countDownDate = new Date($(this).data('deadline')).getTime();
              // Get today's date and time
              var now = new Date().getTime();

              // Find the distance between now and the count down date
              var distance = countDownDate - now;

              // Time calculations for days, hours, minutes and seconds
              var days = Math.floor(distance / (1000 * 60 * 60 * 24));
              var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
              var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
              var seconds = Math.floor((distance % (1000 * 60)) / 1000);
              $(this).children('.day').text(days + 'D');
              $(this).children('.hour').text(hours + 'H');
              $(this).children('.minute').text(minutes + 'M');
              $(this).children('.sec').text(seconds + 'S');

              if (distance < 0) {
                    clearInterval(x);
                    document.getElementById("demo").innerHTML = "EXPIRED";
                  }

              });
                            // If the count down is finished, write some text

                }, 1000);


      </script>
@endpush


@push('style')

     <style>

       .btn--primary{
         background: #ffffff;
         margin-left: 50%;
         transform: translate(-50%, 30%);
       }
        h4.title {
          min-height: 60px;
        }

        .day{
          width: 50px;
          height: 50px;
          border: 2px dashed mediumseagreen;
          border-radius: 50%;
          margin-right: 4px;
          text-align: center;
          font-weight: bolder;
          color: mediumseagreen;
        }

        .hour{
          width: 50px;
          height: 50px;
          border: 2px dashed mediumseagreen;
          border-radius: 50%;
          margin-right: 4px;
          text-align: center;
          font-weight: bolder;
          color: mediumseagreen;
        }
        .minute{
          width: 50px;
          height: 50px;
          border: 2px dashed mediumseagreen;
          border-radius: 50%;
          margin-right: 4px;
          text-align: center;
          font-weight: bolder;
          color: mediumseagreen;
        }
        .sec{
          width: 50px;
          height: 50px;
          border: 2px dashed mediumseagreen;
          border-radius: 50%;
          margin-right: 4px;
          text-align: center;
          font-weight: bolder;
          color: mediumseagreen;
        }
        .days-left > span {
          display: inline-flex;
          align-items: center;
          justify-content: center;
        }
      </style>

@endpush

core/resources/views/templates/basic/sections/donationinfo.blade.php
@extends($activeTemplate.'layouts.master')
@php
    $payment_method = App\Deposit::where('donation_id',$donor->id)->first();
    
@endphp
@section('content')
<div class="container">
    
    <div class="card card-style">
        <div class="card-header">
            <h4 class="card-title text-light">
                <i class="fa fa-list font-style"></i> 
                @lang('Details For Donor of ID')-{{$donor->id}}
            </h4>
        </div>
      <div class="card-body">
      

        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Campaign') : </h3>
            </div>
            <div class="col-md-8">
                <p><a href="{{route('user.campaign.details',['slug'=>$donor->campaign->slug,'id'=>$donor->campaign->id])}}">{{__($donor->campaign->title)}}</a></p>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Full Name') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{__($donor->fullname)}}</p>
            </div>
        </div>
    
    
        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Email') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{__($donor->email)}}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Country') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{__($donor->country)}}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Mobile') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{$donor->mobile}}</p>
            </div>
        </div>

        <hr>
    
    
        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Amount') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{$general->cur_sym}} {{$donor->donation}}</p>
            </div>
        </div>
    
    
        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Payment Method') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{$payment_method->gateway->alias}}</p>
            </div>
        </div>
    

            <hr>
    
        <div class="row">
            <div class="col-md-4">
                <h3>@lang('Payment Date') : </h3>
            </div>
            <div class="col-md-8">
                <p>{{$payment_method->created_at}}</p>
            </div>
        </div>

      </div>


    </div>

</div>

@endsection

@push('style')
    <style>
        .font-style{
            font-size: 25px;
        }
        .card-header{
            background: #16C26B;
        }

        p{
            margin-left: 50px;
            font-size: 18px;
        }
        h3{
            text-align: right;
            font-size: 20px;
        }
        .card-style{
            margin: 50px auto;
            width: 60%;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)

        }
    </style>
@endpush

core/resources/views/templates/basic/sections/footer.blade.php
@php
     $data = getContent('footer.content',true);
     $icon = getContent('social_icon.element',false);
     $policy = getContent('terms.element',false);
     $newsletter = getContent('newsletter.content',true);
     $contact = getContent('contact_us.content',true);

@endphp


<!-- footer section start -->
<footer class="footer-section base--bg position-relative bg_img" data-background="{{get_image('assets/images/frontend/footer/'.$data->data_values->image)}}">
<div class="top-shape"><img src="{{get_image($activeTemplateTrue.'images/top_texture.png')}}" alt="@lang('image')"></div>
    <div class="footer-top">
      <div class="container">
        <div class="row mb-30 align-items-center">
          <div class="col-lg-2 mb-lg-0 mb-5 text-lg-left text-center">
          <a href="#0" class="footer-logo"><img src="{{get_image(imagePath()['logoIcon']['path'].'/'.'logo.png')}}" alt="@lang('image')"></a>
          </div>
          <div class="col-lg-7 col-md-7">
            <div class="row justify-content-center mb-none-30">
              <div class="col-xl-4 col-sm-6 footer-overview-item text-md-left text-center mb-30">
              <h3 class="text-white amount-number text-center">{{App\Donation::where('payment_status',1)->count()}}</h3>
                <p class="text-white text-center">@lang('Total Donate Members')</p>
              </div><!-- footer-overview-item end -->
              <div class="col-xl-4 col-sm-6 footer-overview-item text-md-left text-center mb-30">
                <h3 class="text-white amount-number text-center">{{App\Campaign::where('approval',1)->where('rejected',0)->count()}}</h3>
                <p class="text-white text-center">@lang('Total Campaigns')</p>
              </div><!-- footer-overview-item end -->

              <div class="col-xl-4 col-sm-6 footer-overview-item text-md-left text-center mb-30">
                <h3 class="text-white amount-number text-center">{{$general->cur_sym}} {{App\Donation::where('payment_status',1)->sum('donation')}}</h3>
                <p class="text-white text-center">@lang('Donation Raised')</p>
              </div><!-- footer-overview-item end -->

            </div>
          </div>
          <div class="col-lg-3 col-md-5 mt-md-0 mt-4">
            <div class="text-md-right text-center">
            <a href="{{route('user.campaigns')}}" class="cmn-btn">@lang('Donate Now')</a>
            </div>
          </div>
        </div>
        <hr>
        <div class="row mt-50 mb-none-30 justify-content-center">
          <div class="col-lg-3 col-md-6 col-sm-8 mb-50">
            <div class="footer-widget">
            <h3 class="footer-widget__title">{{__($data->data_values->title)}}</h3>
              <p>{{__($data->data_values->description)}}</p>
              <ul class="social-links mt-4">
                @foreach($icon as $ic)
              <li><a href="{{$ic->data_values->url}}"><?= $ic->data_values->icon ?></a></li>
                @endforeach
              </ul>
              <ul class="company-info-list mt-3">
              <li><a href="tel:{{$contact->data_values->contact_number}}">{{$contact->data_values->contact_number}}</a></li>
              <li><a href="mailto:{{$contact->data_values->email_address}}">{{$contact->data_values->email_address}}</a></li>
              </ul>
            </div><!-- footer-widget end -->
          </div>
          <div class="col-lg-2 col-md-3 col-sm-4 mb-50">
            <div class="footer-widget">
              <h3 class="footer-widget__title">@lang('Our Info')</h3>
              <ul class="short-link-list">
              <li><a href="{{route('user.about')}}">@lang('About Us')</a></li>
              <li><a href="{{route('user.about')}}">@lang('Our Mission')</a></li>
              <li><a href="{{route('user.about')}}">@lang('Our Vision')</a></li>
              </ul>
            </div><!-- footer-widget end -->
          </div>
          <div class="col-lg-2 col-md-3 col-sm-6 mb-50">
            <div class="footer-widget">
            <h3 class="footer-widget__title">@lang('Latest Category')</h3>
              <ul class="short-link-list">
                @foreach(App\Category::whereHas('campaigns',function($q){$q->where('approval',1)->where('expired',0);})->where('mode',1)->latest()->take(3)->get() as $cat)
              <li><a href="{{route('user.campaigns',['category'=>$cat->slug])}}">{{$cat->name}}</a></li>
                
                @endforeach
              </ul>
            </div><!-- footer-widget end -->
          </div>
          <div class="col-lg-2 col-md-6 col-sm-6 mb-50">
            <div class="footer-widget">
              <h3 class="footer-widget__title">@lang('Short Links')</h3>
              <ul class="short-link-list">
              <li><a href="{{route('user.register')}}">@lang('Join With Us')</a></li>
              <li><a href="{{route('user.success.archive')}}">@lang('Our Latest News')</a></li>
              <li><a href="{{route('user.campaigns')}}">@lang('Make Donation')</a></li>
             
              </ul>
            </div><!-- footer-widget end -->
          </div>
          <div class="col-lg-3 col-md-6 mb-50">
            <div class="footer-widget">
              <h3 class="footer-widget__title">{{__($newsletter->data_values->heading)}}</h3>
              <p>{{__($newsletter->data_values->sub_heading)}}</p>
            <form class="subscribe-form mt-3" method="POST" action="{{route('user.subscribe')}}">
                @csrf
                <input type="email" name="email" placeholder="Email Address" class="form-control">
                <button type="submit" id="subscribe"><i class="las la-arrow-right"></i></button>
              </form>
            </div><!-- footer-widget end -->
          </div>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <div class="container">
        <hr>
        <div class="row">
          <div class="col-lg-8 col-md-6 text-md-left text-center">
            <p>@lang('Copyright') © {{\Carbon\Carbon::now()->format('Y')}} | @lang('All Rights Reserved')</p>
          </div>
          <div class="col-lg-4 col-md-6 mt-md-0 mt-3">
            <ul class="link-list justify-content-md-end justify-content-center">
              @foreach($policy as $pol)
            <li><a href="{{route('user.site',$pol->data_values->pagename)}}">{{$pol->data_values->pagename}}</a></li>
              @endforeach
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- footer section end -->


  @push('script')
      <script>
        'use strict';

        $.ajaxSetup({
          headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });


        $(function(){
          

          $('#subscribe').on('click',function(event) {
            event.preventDefault();
            var email = $('input[name=email]').val();
            
              $.ajax({
                      method:'POST',
                      url:"{{route('user.subscribe')}}",
                      data:{email:email},
                      success:function(response){
                          if(response.fails){
                                iziToast.error({
                                message: response.errorMsg.email,
                                position: "topRight"
                            });
                            }

                            if (response.success) {
                                iziToast.success({
                                message: response.successMsg,
                                position: "topRight"
                            });
                            }
                      }
                })
          })


        })
      </script>
  @endpush

core/resources/views/templates/basic/sections/volunteer.blade.php
@php
    $volunteer = getContent('volunteer.content',true);
    $volunteers = App\Volunteer::where('status',1)->get();
@endphp
<!-- volunteer section start -->
    <section class="pt-150 pb-150">\
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="section-header text-center">
              <h2 class="section-title">{{__(@$volunteer->data_values->title)}}</h2>
              <p>{{__(@$volunteer->data_values->description)}}</p>
            </div>
          </div>
        </div>
        <div class="row mb-none-30">
        @foreach ($volunteers as $item)

        <div class="col-xl-3 col-sm-6 mb-30 wow fadeInUp" data-wow-duration="0.3s" data-wow-delay="0.3s">
          <div class="volunteer-card hover--effect-1">
            <div class="volunteer-card__thumb">
              <img src="{{getImage(imagePath()['volunteer']['path'].'/'.$item->image)}}" alt="image" class="w-100">
            </div>
            <div class="volunteer-card__content">
              <img src="{{asset($activeTemplateTrue.'images/top-shape.png')}}" alt="image">
              <h4 class="name">{{$item->fullname}}</h4>
              <span class="designation">@lang("Participate {$item->participated} Campaigns")</span>
            </div>
          </div><!-- volunteer-card end -->
        </div>
        @endforeach

        </div>
      </div>
    </section>
    <!-- volunteer section end -->